### ISSUE TITLE
cinnamon/js problème Perl

### ISSUE THREAD

**Issue by berlius** [NuTyX/cinnamon#2]
**cinnamon/js** :

Un problème dans Perl fait mal nommer notamment le fichier "*mozjs-24.pc*". 
L'équipe de **BLFS** a corrigé par un sed sur "config/milestone.pl"(http://www.linuxfromscratch.org/blfs/view/svn/general/JS2.html). 
Donc il faut faire pareil sinon le suivant **cinnamon/cjs** ne passe pas. 

Le patch est : 

--- Pkgfile	2015-11-06 15:53:25.000000000 +0100
+++ Pkgfile1	2015-11-06 21:31:20.000000000 +0100
@@ -12,6 +12,9 @@
 build() {
 unset CPPFLAGS
 cd mozjs-$version/js/src
\+
\+sed -i 's/(defined\((@TEMPLATE_FILE)\))/\1/' config/milestone.pl
\+
 SHELL=/bin/sh ./configure --prefix=/usr --with-system-nspr --enable-system-ffi \
 --enable-readline --enable-threadsafe
 make

**Comment by tnut** [comment]
Js peut être supprimé, déjà dispo

**Comment by berlius** [comment]
Si tu laisses ainsi "cinnamon/cjs" ne compile pas car "mozjs-24.pc" est généré par "cinnamon/js" en "mozjs-.pc". Il ne trouve pas la librairie. 


     On Saturday, November 7, 2015 12:42 PM, tnut <notifications@github.com> wrote:
   

 Closed #2.—
